# Site settings
title: Animal Fun
email: marenrosepetal@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website about exploring animals in nature.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marenrose.com" # the base hostname & protocol for your site
github_username:  marenrose

# Build settings
markdown: kramdown
